In [1]:
l=[1,2,3,4]

In [2]:
print(l)

[1, 2, 3, 4]


In [8]:
print(type(l))

<class 'list'>


In [3]:
l+5

TypeError: can only concatenate list (not "int") to list

In [4]:
import numpy as np

In [5]:
a=np.array(l)

In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
a+5

array([6, 7, 8, 9])

In [10]:
print(a.size)

4


In [11]:
print(len(a))

4


In [12]:
print(a.dtype)

int32


In [29]:
#typecasting (int-> float)

In [14]:
print(a.astype(float))

[1. 2. 3. 4.]


In [16]:
b=a.astype(float)

In [20]:
print(b)

[1. 2. 3. 4.]


In [17]:
print(a.dtype)

int32


In [18]:
print(b.dtype)

float64


In [26]:
s=a.astype(str)

In [27]:
print(s)

['1' '2' '3' '4']


In [28]:
print(s.dtype)

<U11


In [31]:
print(a)

[1 2 3 4]


In [32]:
print(a.ndim)

1


In [33]:
print(len(a))

4


In [34]:
#2d array

In [48]:
d=np.array([[1,2,3]])

In [49]:
print(d)

[[1 2 3]]


In [51]:
print(d.ndim)

2


In [52]:
print(len(d))

1


In [53]:
print(d.size)

3


In [54]:
d1=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [55]:
print(d1.ndim)

2


In [56]:
print(len(d1))

3


In [57]:
print(d1.size)

9


In [58]:
print(type(d1))

<class 'numpy.ndarray'>


In [59]:
d2=d1*5

In [61]:
d2

array([[ 5, 10, 15],
       [ 5, 10, 15],
       [ 5, 10, 15]])

In [62]:
print(d2)

[[ 5 10 15]
 [ 5 10 15]
 [ 5 10 15]]
