In [23]:
import numpy as np

In [30]:
#creating an numpy array
arr=np.array([1,2,3,4])

In [25]:
arr

array([1, 2, 3, 4])

In [26]:
type(arr)

numpy.ndarray

In [27]:
#array is faster than list "locality of referece"

In [28]:
print(arr)

[1 2 3 4]


In [29]:
print(np.__version__)

1.24.3


In [31]:
#Dimension in Array

In [32]:
#0-D Array or scalars

In [33]:
ad=np.array(34)

In [36]:
print(ad)


34


In [37]:
#1 D array or uni dimensional

In [38]:
arr=np.array([1,2,3,4])

In [39]:
print(arr)

[1 2 3 4]


In [57]:
print(arr.ndim)

1


In [40]:
#2D array

In [47]:
a=np.array([[1,2,3],[5,6,7]])

In [58]:
print(a.ndim)

2


In [48]:
print(a)

[[1 2 3]
 [5 6 7]]


In [49]:
#3D array

In [55]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [56]:
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [59]:
print(arr1.ndim)

3


In [112]:
a1=np.array([10,20,30],ndmin=3)

In [113]:
print(a1.shape)

(1, 1, 3)


In [114]:
print('number of dimensions :',a1.ndim)

number of dimensions : 3


In [68]:
#Numpy Array Elements

In [69]:
a2=np.array([1,2,3,4])

In [72]:
print(a2[3])

4


In [73]:
print(a2[2] + a2[3])

7


In [81]:
a=np.array([[1,2,3],[5,6,7]])

In [82]:
print(a)

[[1 2 3]
 [5 6 7]]


In [115]:
print(a.shape)

(2, 3)


In [78]:
print('2nd element on 1st row: ' ,a[0,1])

2nd element on 1st row:  2


In [84]:
print('3nd element on 2nd row: ' ,a[1,2])

3nd element on 2nd row:  7


In [85]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [86]:
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [91]:
print(arr1[0,1,1])

5


In [93]:
#negative indexing: access an array from the end

In [94]:
a=np.array([[1,2,3],[5,6,7]])

In [98]:
print('last element from 2nd dim: ',a[1,-1])

last element from 2nd dim:  7


In [100]:
a.ndim

2

In [103]:
np.shape(a)

(2, 3)

In [104]:
print('last element from 2nd dim: ',a[-1,-1])

last element from 2nd dim:  7


In [105]:
print(a[0,1])

2


In [106]:
print(a[0][1])

2


In [107]:
#slicing arrays[start:end:step]

In [116]:
arr=np.array([1,2,3,4])

In [120]:
print(arr[0:])

[1 2 3 4]


In [121]:
print(arr[:])

[1 2 3 4]


In [122]:
print(arr[:2])

[1 2]


In [123]:
#Negative slicing

In [ ]:
arr=np.array([1,2,3,4])

In [124]:
print(arr[-3:-1])

[2 3]


In [125]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [126]:
print(arr.shape)

(9,)


In [129]:
arr[2:-1]

array([3, 4, 5, 6, 7, 8])

In [131]:
arr[2:-1:2]

array([3, 5, 7])

In [133]:
arr[::3]

array([1, 4, 7])

In [134]:
#slicing 2-D Arrays

In [141]:
a=np.array([[1,2,3,4,8],[5,6,7,45,67]])

In [142]:
print(a)

[[ 1  2  3  4  8]
 [ 5  6  7 45 67]]


In [148]:
#columns
print(a[0:2,2])

[3 7]


In [151]:
#row
print(a[1, 1:4])

[ 6  7 45]


In [152]:
print(a[0:2,1:4])

[[ 2  3  4]
 [ 6  7 45]]


In [154]:
print(a[0:2,-2:])

[[ 4  8]
 [45 67]]


In [155]:
print(a[0:2,3:])

[[ 4  8]
 [45 67]]


In [157]:
# datatypes in numpy
strings -S
integers -i
float -f
boolean -b
complex - c

NameError: name 'strings' is not defined

In [158]:
arr=np.array([1,2,3,4])

In [159]:
print(arr.dtype)

int32


In [162]:
ars=np.array(['a', 'b','c'])

In [163]:
print(ars.dtype)

<U1


In [164]:
arr=np.array([1,2,3,4], dtype='S')

In [165]:
print(arr.dtype)

|S1


In [166]:
arr=np.array([1,2,3,4], dtype='i4')

In [167]:
print(arr.dtype)

int32


In [169]:
arr=np.array(['1','2','3','4'], dtype='i')

In [170]:
af=np.array([1.1,2.1,3.1])

In [171]:
af.dtype

dtype('float64')

In [172]:
newaf=af.astype('i')

In [173]:
newaf.dtype

dtype('int32')

In [174]:
#numpy array reshapping

In [176]:
#Reshape from 1D to 2D

In [179]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [180]:
print(arr.shape)

(12,)


In [181]:
newarr=arr.reshape(4,3)

In [182]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [183]:
newarr.shape

(4, 3)

In [184]:
arr=np.array([1,2,3,4,5,6,7,8])

In [185]:
arr.shape

(8,)

In [196]:
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


In [191]:
newarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [199]:
a= input()
print(ord(a))

a
97
